version: '3.0'
services:
  web:
    container_name: nodeapp
    build: .
    ports:
      - 3000:3000
    environment:
        PRODUCTION: 'true'
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
          - 5000:5000
