version: '3.0'
services:
#  web:
#    container_name: nodeapp
#    build: .
#    ports:
#      - 3000:3000
#    environment:
#      - DEBUG=1
  nginx:
    extra_hosts:
     - "local:192.168.1.232"
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
          - 3000:3000
